Repository honeycombio/buildevents-orb, pull requests merged in 2022-01, with the labels that each got.

#57 lightweight command to create a build marker
  orb.yml
Labels: type: enhancement, version: bump minor

#59 Update build events to 0.7.2
  orb.yml
Labels: version: bump patch, type: maintenance

#60 Bump buildevents to 0.8.0
  orb.yml
Labels: version: bump minor, type: maintenance

#58 Prepare 0.5.0 release
  CHANGELOG.md
Labels: version: bump minor, type: maintenance
